name: Backend Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend-checks:
    name: Backend Linting, Types, and Tests (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x', '21.x']
    
    # Add MySQL service container
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: dappykit_apps
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install root dependencies
        run: npm ci
        
      - name: Install backend dependencies
        run: cd backend && npm ci
        
      - name: Check formatting (backend only)
        run: npm run format:backend
        
      - name: Lint check (backend only)
        run: npm run lint:backend
        
      - name: Type check
        run: cd backend && npx tsc --noEmit --project tsconfig.json
        
      # Add environment variables for MySQL connection
      - name: Run tests
        run: npm run backend:test
        env:
          DB_HOST: localhost
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: dappykit_apps 